# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :centos_node1 do |node1|
    node1.vm.box = "centos1706v2"
    node1.vm.network :private_network, ip: "192.168.56.101"
    node1.vm.network "public_network", bridge: "eno1", ip:"192.168.131.27", netmask: "255.255.255.0"
    node1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_node1" ]
    end
  end
  config.vm.define :centos_node2 do |node2|
    node2.vm.box = "centos1706v2"
    node2.vm.network :private_network, ip: "192.168.56.102"
    node2.vm.network "public_network", bridge: "eno1", ip:"192.168.131.31", netmask: "255.255.255.0"
    node2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_node2" ]
    end
    server.vm.provision "shell", inline: <<-SHELL
      sudo yum install screen vim -y
      echo '[sensu]
name=sensu
baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
gpgcheck=0
enabled=1' | sudo tee /etc/yum.repos.d/sensu.repo
      su -c 'rpm -Uvh http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-3.6.9-1.el7.noarch.rpm'
      service rabbitmq-server start
      sudo rabbitmqctl add_vhost /sensu
      sudo rabbitmqctl add_user sensu password
      sudo rabbitmqctl set_permissions -p /sensu sensu ".*" ".*" ".*"
      rabbitmq-plugins enable rabbitmq_management
      chown -R rabbitmq:rabbitmq /var/lib/rabbitmq/
      rabbitmqctl add_user test test
      rabbitmqctl set_user_tags test administrator
      rabbitmqctl set_permissions -p / test ".*" ".*" ".*"
    SHELL
  end
end
